# This is a development compose.yml. Use the one in examples/compose.yml to bootstrap a template for your project
services:
  bmde-linux:
    image: aleixmt/bmde-linux:latest
    container_name: bmde-linux
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/input
    entrypoint: sh -c "cd /input && make clean && make"
    user: 1000:1000


